# 端口 8088
server:
  port: 8088
spring:
  # 应用信息
  application:
    name: taco
  # 数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.0.198:3306/taco?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345
    druid:
      initial-size: 5
      max-active: 10
      max-wait: 3000
      min-idle: 3
      test-on-borrow: false
      test-while-idle: true
      test-on-return: false
      validation-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# 持久化框架
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: taco.pojo
